repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace

  - repo: git://github.com/igorshubovych/markdownlint-cli
    sha: v0.6.0
    hooks:
      - id: markdownlint

  - repo: git://github.com/detailyang/pre-commit-shell
    sha: 1.0.2
    hooks:
      - id: shell-lint

  - repo: git://github.com/kintoandar/pre-commit.git
    sha: v2.1.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
